### ISSUE TITLE
gggg

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#139]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd8da8c2c3316d6387767769b0ae6f7e2ba5427cec3eb13dfb89c7e9d02ef4fed](https://ropsten.etherscan.io/tx/0xd8da8c2c3316d6387767769b0ae6f7e2ba5427cec3eb13dfb89c7e9d02ef4fed)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe6e41636af150100e6fd3ab908487e555cabaa9d0072ac12c144d9070d7b83ba](https://ropsten.etherscan.io/tx/0xe6e41636af150100e6fd3ab908487e555cabaa9d0072ac12c144d9070d7b83ba)
