### ISSUE TITLE
FIRST long name issue FIRST long name issueFIRST long name issueFIRST long name issue     FIRST long name issueFIRST long name issueFIRST long name issueFIRST long name issueFIRST long name issue FIRST long name issue FIRST long name issueFIRST long name issueFIRST long name issue     FIRST long name issueFIRST long name issueFIRST long name issueFIRST long name issueFIRST long name issue

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#179]
FIRST long name issue

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc1397e760b8b0ad400fcd94381ebb454bbb59598b320eb152cebece6245e9a60](https://ropsten.etherscan.io/tx/0xc1397e760b8b0ad400fcd94381ebb454bbb59598b320eb152cebece6245e9a60)
