### ISSUE TITLE
Issue 2

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#180]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x1bbd7f766e1049889696d84dc800784d2a48461b9cec282009de3b2f1b8c682a](https://ropsten.etherscan.io/tx/0x1bbd7f766e1049889696d84dc800784d2a48461b9cec282009de3b2f1b8c682a)
