### ISSUE TITLE
1 issue -> 1 PR один ишью, один пр

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#181]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x01b77b9499b782dec15353eaf072142e8068065f4fe1bbf792b3a74bc7c3fab6](https://ropsten.etherscan.io/tx/0x01b77b9499b782dec15353eaf072142e8068065f4fe1bbf792b3a74bc7c3fab6)
