### ISSUE TITLE
1 issue-> several PRs

### ISSUE THREAD

**Issue by churik** [TestingEnvENV/TestEnvAtt5_1#183]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xebb511698e12115441072c5e512c379ab2729636f8d291ff3b15b4e13b930678](https://ropsten.etherscan.io/tx/0xebb511698e12115441072c5e512c379ab2729636f8d291ff3b15b4e13b930678)
