### ISSUE TITLE
dddddd

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#190]
dddddd

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8d16493f796213ca11ef6f279ce0e53cae1599029016f88e06bfa772cacc62d7](https://ropsten.etherscan.io/tx/0x8d16493f796213ca11ef6f279ce0e53cae1599029016f88e06bfa772cacc62d7)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x976e93e40db43b1d2aea5238eee31b052e8be2026c757e309ee08492d4073d96](https://ropsten.etherscan.io/tx/0x976e93e40db43b1d2aea5238eee31b052e8be2026c757e309ee08492d4073d96)
