### ISSUE TITLE
ddd

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#191]
dddd

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd5dc0b59fe5bdd916929f37e56f775b94e89fadc8bb36efc84c6b2dbd9cda628](https://ropsten.etherscan.io/tx/0xd5dc0b59fe5bdd916929f37e56f775b94e89fadc8bb36efc84c6b2dbd9cda628)
