### ISSUE TITLE
To claim all; to create PR after merge

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#195]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xae356999cea56d38575396d025e6a5e5f7853cceef00a1ca9ce766c92cd3d4eb](https://ropsten.etherscan.io/tx/0xae356999cea56d38575396d025e6a5e5f7853cceef00a1ca9ce766c92cd3d4eb)
