### ISSUE TITLE
Issue to test bounty revoke

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#249]
Issue to test bounty revoke

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x853f7538d4a00ed06252b5867b167cb121d16b2ddbcc0e43ed5cf62d58453caa](https://ropsten.etherscan.io/tx/0x853f7538d4a00ed06252b5867b167cb121d16b2ddbcc0e43ed5cf62d58453caa)
