### ISSUE TITLE
RevokeSNTonly

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#250]
RevokeSNTonly

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x1d6db1bfc0010eff6332b721e8bf3a9111c1b30db61885dacd573aa479ec47b2](https://ropsten.etherscan.io/tx/0x1d6db1bfc0010eff6332b721e8bf3a9111c1b30db61885dacd573aa479ec47b2)
