### ISSUE TITLE
issueToRevoke SNT only

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#251]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x59471f2320d4ab43946d8ec494070a62d8ca947d7b58e845846c1f48a8a3db8c](https://ropsten.etherscan.io/tx/0x59471f2320d4ab43946d8ec494070a62d8ca947d7b58e845846c1f48a8a3db8c)
