### ISSUE TITLE
issueToRevoke SNT+ETH

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#252]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8083322298a8a133418382fb12ce7825d7ebfdfd32466da7beeb214f6047939b](https://ropsten.etherscan.io/tx/0x8083322298a8a133418382fb12ce7825d7ebfdfd32466da7beeb214f6047939b)
