### ISSUE TITLE
TOrevoke ETH only

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#253]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf29f71d929b720419e253fa651316ecb48c8d4b71505fe9359070f3d43003371](https://ropsten.etherscan.io/tx/0xf29f71d929b720419e253fa651316ecb48c8d4b71505fe9359070f3d43003371)
