### ISSUE TITLE
TOrevoke ATT

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#254]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf9b3bd163cae3bd25d7cfbfa712afe358407a2af394ab7e4e968bbf32492580f](https://ropsten.etherscan.io/tx/0xf9b3bd163cae3bd25d7cfbfa712afe358407a2af394ab7e4e968bbf32492580f)
