### ISSUE TITLE
1 SNT - to revoke

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#255]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe9fe4d99de81267cb39b269e25b133dca61ccd293b4ee94cd83c87dc819c299b](https://ropsten.etherscan.io/tx/0xe9fe4d99de81267cb39b269e25b133dca61ccd293b4ee94cd83c87dc819c299b)
