### ISSUE TITLE
2 SNT - to revoke

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#256]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc84707a4eb8c65ec26f5e29f2792ee05df10046fca5e9a12939d9547b8ca571a](https://ropsten.etherscan.io/tx/0xc84707a4eb8c65ec26f5e29f2792ee05df10046fca5e9a12939d9547b8ca571a)
