### ISSUE TITLE
ATT - one more

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#257]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa3ce895845ca9510e598147b12602c76b440d1f9be2b3cabb8a9a83afb89ccb2](https://ropsten.etherscan.io/tx/0xa3ce895845ca9510e598147b12602c76b440d1f9be2b3cabb8a9a83afb89ccb2)
