### ISSUE TITLE
1000 ATT

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#258]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x05cf3633ef44dcca6d0a63724bb957d5031a065beceaa756f3326825c6638a4c](https://ropsten.etherscan.io/tx/0x05cf3633ef44dcca6d0a63724bb957d5031a065beceaa756f3326825c6638a4c)
