### ISSUE TITLE
to update address before revocation

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#259]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x667f223dec39e6af881f5e900c40c4330eb234e313770f960bc5f1d51821709f](https://ropsten.etherscan.io/tx/0x667f223dec39e6af881f5e900c40c4330eb234e313770f960bc5f1d51821709f)
