### ISSUE TITLE
just to confirm

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#260]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x7557ae013cc52b6976839a8f1037c32a690c24ac690c11896e6f8407017a8df5](https://ropsten.etherscan.io/tx/0x7557ae013cc52b6976839a8f1037c32a690c24ac690c11896e6f8407017a8df5)
