### ISSUE TITLE
TEST: revoc SNT

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#262]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x65b94a14143c7c0e4907848cd9a7c6417fdddb2f78a20e0d3325f1e99fd9deae](https://ropsten.etherscan.io/tx/0x65b94a14143c7c0e4907848cd9a7c6417fdddb2f78a20e0d3325f1e99fd9deae)
