### ISSUE TITLE
SNT only

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#264]
SNT only

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x63953228edb25d16b68ca2c1f204301d5496f5a4f65a38ea6fd79efcd71b8d96](https://ropsten.etherscan.io/tx/0x63953228edb25d16b68ca2c1f204301d5496f5a4f65a38ea6fd79efcd71b8d96)
