### ISSUE TITLE
SNT only 2

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#265]
SNT only 2

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd433144e8b7fc8430ccd93608a9452886dc5e8480381b846c391f19a77a9a820](https://ropsten.etherscan.io/tx/0xd433144e8b7fc8430ccd93608a9452886dc5e8480381b846c391f19a77a9a820)
