### ISSUE TITLE
New_SNT_only

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#273]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa8ba0787f6c77e6a1d8fa711396a708089f62c46217a892c9781ae8ecf542a12](https://ropsten.etherscan.io/tx/0xa8ba0787f6c77e6a1d8fa711396a708089f62c46217a892c9781ae8ecf542a12)
