### ISSUE TITLE
New SNT_ETH 1234567890123456789012345678901234567890 123456789012345678901234567890 12345678901234567890

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#274]
New SNT_ETH

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe8c744128bc6be9eaa77ea153a2aaf495083c1254eca4f581dfb19e6acd7cec7](https://ropsten.etherscan.io/tx/0xe8c744128bc6be9eaa77ea153a2aaf495083c1254eca4f581dfb19e6acd7cec7)
