### ISSUE TITLE
Small_amount

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5_1#297]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x9e190b8923e62946bd444e7a3bed3851f7c22012a623c64695a7cd4f0d1c369f](https://ropsten.etherscan.io/tx/0x9e190b8923e62946bd444e7a3bed3851f7c22012a623c64695a7cd4f0d1c369f)
